#!/bin/bash
#/etc/init.d/rssh

cd /home/yebin/pyprojects/rssh

### BEGIN INIT INFO
# Provides:          rssh
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: rssh
# Description:       start rssh service
### END INIT INFO

case "$1" in
    start)
        echo "Starting rssh service..."
        python start.py
        ;;
    stop)
        echo "Stopping rssh service..."
        kill $(ps aux | grep '/home/yebin/pyprojects/rssh/rsshd.py' | awk '{print $2}')
        ;;
    *)
        echo "Usage: /etc/init.d/rssh{start|stop}"
        exit 1
        ;;
esac

exit 0
