#!/bin/bash
#/etc/init.d/myblog

### BEGIN INIT INFO
# Provides:          myblog
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: myblog
# Description:       myblog pop & imap daemon
### END INIT INFO

case "$1" in
    start)
        echo "Starting myblog..."
        /home/yebin/pyprojects/myblog/.venv/bin/python /home/yebin/pyprojects/myblog/app.py > /dev/null 2>&1 &
        ;;
    stop)
        echo "Stopping myblog..."
        killall /home/yebin/pyprojects/myblog/.venv/bin/python
        ;;
    *)
        echo "Usage: /etc/init.d/myblog{start|stop}"
        exit 1
        ;;
esac

exit 0
