#!/bin/bash
#/etc/init.d/messageboard

case "$1" in
    start)
        echo "Starting messageboard ..."
        /home/yebin/gitcode/messageboard/.venv/bin/python /home/yebin/gitcode/messageboard/messageboard.py > /dev/null 2>&1 &
        ;;
    stop)
        echo "Stopping messageboard ..."
        killall /home/yebin/gitcode/messageboard/.venv/bin/python
        ;;
    *)
        echo "Usage: /etc/init.d/messageboard{start|stop}"
        exit 1
        ;;
esac

exit 0
