#!/bin/bash
#/etc/init.d/monitor

### BEGIN INIT INFO
# Provides:          monitor
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: monitor
# Description:       monitor pop & imap daemon
### END INIT INFO

case "$1" in
    start)
        echo "Starting monitor service..."
        /home/yebin/pyprojects/monitor/.venv/bin/python /home/yebin/pyprojects/monitor/app.py > /dev/null 2>&1 &
        ;;
    stop)
        echo "Stopping monitor service..."
        killall /home/yebin/pyprojects/monitor/.venv/bin/python
        ;;
    *)
        echo "Usage: /etc/init.d/monitor{start|stop}"
        exit 1
        ;;
esac

exit 0
