#!/bin/bash
#/etc/init.d/mainpage

cd /home/yebin/pyprojects/mainpage

### BEGIN INIT INFO
# Provides:          mainpage
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: mainpage
# Description:       start mainpage service
### END INIT INFO

case "$1" in
    start)
        echo "Starting mainpage service..."
        python start.py
        ;;
    stop)
        echo "Stopping mainpage service..."
        kill $(ps aux | grep '/home/yebin/pyprojects/mainpage/app.py' | awk '{print $2}')
        ;;
    *)
        echo "Usage: /etc/init.d/mainpage{start|stop}"
        exit 1
        ;;
esac

exit 0
